// 아이콘 레지스트리 (디자인 v2): 모든 UI 아이콘은 lucide 라인 아이콘 + currentColor — 색 있는 이모지 아이콘은 쓰지 않는다.
// 컴포넌트에서는 lucide-react 를 바로 import 해도 되고, 데이터(lib/*)가 아이콘을 고를 때는 이 이름(IconName)을 쓴다.
import {
  Amphora,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  Award,
  Backpack,
  Bean,
  Beef,
  BookOpen,
  BookUser,
  Bookmark,
  Brain,
  Cake,
  CalendarClock,
  Camera,
  Carrot,
  ChartColumn,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleQuestionMark,
  Citrus,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  Croissant,
  Drumstick,
  Ear,
  Earth,
  EggFried,
  ExternalLink,
  Fish,
  Flag,
  Flame,
  Globe,
  Hamburger,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Image as ImageIcon,
  ImagePlus,
  Info,
  KeyRound,
  Leaf,
  LeafyGreen,
  Link,
  LocateFixed,
  Map as MapIcon,
  MapPin,
  MapPinned,
  MessageCircle,
  Medal,
  Minus,
  Mic,
  Milk,
  Moon,
  Navigation,
  Newspaper,
  Package,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Pizza,
  Plane,
  Plus,
  Play,
  Radio,
  RotateCcw,
  Route,
  Salad,
  Sandwich,
  Search,
  Send,
  Settings,
  Share2,
  Shrimp,
  Snail,
  Soup,
  Sparkles,
  Square,
  Stamp,
  Star,
  Sun,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Trophy,
  TriangleAlert,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  Wheat,
  X,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

export const ICONS = {
  // 내비게이션
  home: House,
  mic: Mic,
  passport: BookUser,
  map: MapIcon,
  pin: MapPin,
  "map-pinned": MapPinned,
  radio: Radio,
  headphones: Headphones,
  table: UtensilsCrossed,
  quest: Trophy,
  back: ChevronLeft,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  next: ChevronRight,
  search: Search,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  user: User,
  external: ExternalLink,
  locate: LocateFixed,
  navigation: Navigation,
  phone: Phone,
  users: Users,
  // 동작
  play: Play,
  pause: Pause,
  stop: Square,
  replay: RotateCcw,
  close: X,
  check: Check,
  "check-circle": CircleCheck,
  circle: Circle,
  edit: Pencil,
  share: Share2,
  camera: Camera,
  "image-plus": ImagePlus,
  plus: Plus,
  send: Send,
  trash: Trash2,
  link: Link,
  "thumbs-up": ThumbsUp,
  message: MessageCircle,
  poll: ChartColumn,
  calendar: CalendarClock,
  trending: TrendingUp,
  newspaper: Newspaper,
  up: ArrowUp,
  down: ArrowDown,
  minus: Minus,
  image: ImageIcon,
  "volume-on": Volume2,
  "volume-off": VolumeX,
  wave: AudioLines,
  // 상태·정보
  info: Info,
  warn: TriangleAlert,
  help: CircleQuestionMark,
  sparkle: Sparkles,
  package: Package,
  flag: Flag,
  star: Star,
  key: KeyRound,
  // 설정 (AI 두뇌 · 음성)
  brain: Brain,
  ear: Ear,
  zap: Zap,
  snail: Snail,
  coins: Coins,
  // Passport 상태
  heart: Heart,
  bookmark: Bookmark,
  stamp: Stamp,
  book: BookOpen,
  // 탐험·퀘스트·배지
  compass: Compass,
  globe: Globe,
  earth: Earth,
  plane: Plane,
  backpack: Backpack,
  route: Route,
  flame: Flame,
  medal: Medal,
  award: Award,
  trophy: Trophy,
  party: PartyPopper,
  leaf: Leaf,
  // 음식 모양 (My Table 접시 · 퀘스트 · 라디오 채널)
  utensils: Utensils,
  soup: Soup,
  pot: CookingPot,
  jar: Amphora,
  salad: Salad,
  greens: LeafyGreen,
  shrimp: Shrimp,
  fish: Fish,
  beef: Beef,
  drumstick: Drumstick,
  wheat: Wheat,
  bean: Bean,
  bread: Croissant,
  sandwich: Sandwich,
  burger: Hamburger,
  pizza: Pizza,
  egg: EggFried,
  cake: Cake,
  dessert: IceCreamCone,
  coffee: Coffee,
  citrus: Citrus,
  carrot: Carrot,
  milk: Milk,
  chef: ChefHat,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** 기본 굵기 1.75 — 레퍼런스의 얇은 라인 톤. 색은 부모 글자색을 따른다 */
export function Icon({ name, className = "size-5", strokeWidth = 1.75, ...rest }: { name: IconName } & LucideProps) {
  const C = ICONS[name];
  return <C aria-hidden className={className} strokeWidth={strokeWidth} {...rest} />;
}
