// 아이콘 레지스트리 (디자인 v2): 모든 UI 아이콘은 lucide 라인 아이콘 + currentColor — 색 있는 이모지 아이콘은 쓰지 않는다.
// 컴포넌트에서는 lucide-react 를 바로 import 해도 되고, 데이터(lib/*)가 아이콘을 고를 때는 이 이름(IconName)을 쓴다.
import {
  Amphora,
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Award,
  Backpack,
  Bean,
  Beef,
  BookOpen,
  BookUser,
  Bookmark,
  Cake,
  Camera,
  Carrot,
  Check,
  ChefHat,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleQuestionMark,
  Citrus,
  Coffee,
  Compass,
  CookingPot,
  Croissant,
  Drumstick,
  Earth,
  EggFried,
  Fish,
  Flame,
  Globe,
  Hamburger,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Image as ImageIcon,
  Info,
  Leaf,
  LeafyGreen,
  Map as MapIcon,
  MapPin,
  Medal,
  Mic,
  Milk,
  Package,
  PartyPopper,
  Pause,
  Pencil,
  Pizza,
  Plane,
  Play,
  Radio,
  RotateCcw,
  Route,
  Salad,
  Sandwich,
  Search,
  Settings,
  Share2,
  Shrimp,
  Soup,
  Sparkles,
  Stamp,
  Trophy,
  TriangleAlert,
  User,
  Utensils,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  Wheat,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

export const ICONS = {
  // 내비게이션
  home: House,
  mic: Mic,
  passport: BookUser,
  map: MapIcon,
  pin: MapPin,
  radio: Radio,
  headphones: Headphones,
  table: UtensilsCrossed,
  quest: Trophy,
  back: ChevronLeft,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  next: ChevronRight,
  search: Search,
  settings: Settings,
  user: User,
  // 동작
  play: Play,
  pause: Pause,
  replay: RotateCcw,
  close: X,
  check: Check,
  "check-circle": CircleCheck,
  edit: Pencil,
  share: Share2,
  camera: Camera,
  image: ImageIcon,
  "volume-on": Volume2,
  "volume-off": VolumeX,
  wave: AudioLines,
  // 상태·정보
  info: Info,
  warn: TriangleAlert,
  help: CircleQuestionMark,
  sparkle: Sparkles,
  package: Package,
  // Passport 상태
  heart: Heart,
  bookmark: Bookmark,
  stamp: Stamp,
  book: BookOpen,
  // 탐험·퀘스트·배지
  compass: Compass,
  globe: Globe,
  earth: Earth,
  plane: Plane,
  backpack: Backpack,
  route: Route,
  flame: Flame,
  medal: Medal,
  award: Award,
  trophy: Trophy,
  party: PartyPopper,
  leaf: Leaf,
  // 음식 모양 (My Table 접시 · 퀘스트 · 라디오 채널)
  utensils: Utensils,
  soup: Soup,
  pot: CookingPot,
  jar: Amphora,
  salad: Salad,
  greens: LeafyGreen,
  shrimp: Shrimp,
  fish: Fish,
  beef: Beef,
  drumstick: Drumstick,
  wheat: Wheat,
  bean: Bean,
  bread: Croissant,
  sandwich: Sandwich,
  burger: Hamburger,
  pizza: Pizza,
  egg: EggFried,
  cake: Cake,
  dessert: IceCreamCone,
  coffee: Coffee,
  citrus: Citrus,
  carrot: Carrot,
  milk: Milk,
  chef: ChefHat,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** 기본 굵기 1.75 — 레퍼런스의 얇은 라인 톤. 색은 부모 글자색을 따른다 */
export function Icon({ name, className = "size-5", strokeWidth = 1.75, ...rest }: { name: IconName } & LucideProps) {
  const C = ICONS[name];
  return <C aria-hidden className={className} strokeWidth={strokeWidth} {...rest} />;
}
